### ISSUE TITLE
When the value of vstart written through the csr instruction is greater than the vlmax under the current configuration, whether the hardware can be treated as an illegal instruction to implement

### ISSUE THREAD

**Issue by Wei-VV1995** [riscv/riscv-v-spec#904] opened 2023-07-17 08:01 UTC
“The use of vstart values greater than the largest element index for the current SEW setting is reserved”
When the value of vstart written through the csr instruction is greater than the vlmax under the current configuration, whether the hardware can be treated as an illegal instruction to implement？

**Comment by aswaterman** [comment] 2023-07-17 23:56
Yeah, in general, reserved behaviors can be implemented as an illegal-instruction exception.

**Comment by Wei-VV1995** [comment] 2023-07-18 01:57
Thank you very much for your answer !

**Comment by Wei-VV1995** [comment] 2023-07-31 01:45
> Yeah, in general, reserved behaviors can be implemented as an illegal-instruction exception.
If vtype=1, is vlamx equal to 0? If vlamx=0, then any value configured for vstart is treated as an illegal instruction, because in this case, any vstart value is greater than the element index.

**Comment by Wei-VV1995** [comment] 2023-07-31 01:45
If vtype=1, is vlamx equal to 0? If vlamx=0, then any value configured for vstart is treated as an illegal instruction, because in this case, any vstart value is greater than the element index.

**Comment by aswaterman** [comment] 2023-08-01 01:27
Duplicate of #907

**Closed by aswaterman** 2023-08-01 01:27 UTC
